export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const EVENTS = {
    REQUEST: 'EVENTS_REQUEST',
    SUCCESS: 'EVENTS_SUCCESS',
    FAILURE: 'EVENTS_FAILURE'
};

export const ACTIVITIES = {
    REQUEST: 'ACTIVITIES_REQUEST',
    SUCCESS: 'ACTIVITIES_SUCCESS',
    FAILURE: 'ACTIVITIES_FAILURE'
};
